"""Add background_color to Map model

Revision ID: 5db8e7ec38e6
Revises: 3bb35bb39457
Create Date: 2024-10-10 18:37:19.003610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db8e7ec38e6'
down_revision = '3bb35bb39457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###
