"""Add z_coord to Item model

Revision ID: 045e30d4a92f
Revises: 8559733275ff
Create Date: 2024-10-22 15:04:17.436378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045e30d4a92f'
down_revision = '8559733275ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_coord_model', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('y_coord_model', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('z_coord_model', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('z_coord_model')
        batch_op.drop_column('y_coord_model')
        batch_op.drop_column('x_coord_model')

    # ### end Alembic commands ###
