"""Recovery baseline for fresh databases

Revision ID: 07bc433eb115
Revises: 
Create Date: 2026-09-13 21:15:07.773910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bc433eb115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('svg_path', sa.String(length=300), nullable=False),
    sa.Column('model_path', sa.String(length=300), nullable=True),
    sa.Column('background_color', sa.String(length=30), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=False),
    sa.Column('x_coord', sa.Float(), nullable=True),
    sa.Column('y_coord', sa.Float(), nullable=True),
    sa.Column('x_coord_model', sa.Float(), nullable=True),
    sa.Column('y_coord_model', sa.Float(), nullable=True),
    sa.Column('z_coord_model', sa.Float(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('warning', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recovery_key', sa.String(length=64), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('available','needs_review','archived')", name='valid_status'),
    sa.CheckConstraint('quantity >= 0', name='nonnegative_quantity'),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_key')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_map_id'), ['map_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_status'), ['status'], unique=False)

    op.create_table('mesh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mesh', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mesh_map_id'), ['map_id'], unique=False)

    op.create_table('item_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_history_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_history_item_id'))

    op.drop_table('item_history')
    with op.batch_alter_table('mesh', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mesh_map_id'))

    op.drop_table('mesh')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_status'))
        batch_op.drop_index(batch_op.f('ix_item_name'))
        batch_op.drop_index(batch_op.f('ix_item_map_id'))

    op.drop_table('item')
    op.drop_table('map')
    # ### end Alembic commands ###
