"""Add map_id to Item model

Revision ID: 3bb35bb39457
Revises: 
Create Date: 2024-10-10 12:32:55.328346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb35bb39457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'map', ['map_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('map_id')

    # ### end Alembic commands ###
