"""Add more keys

Revision ID: 7ff64898908d
Revises: c4998c991b24
Create Date: 2024-10-14 19:21:08.777047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff64898908d'
down_revision = 'c4998c991b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('zone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('warning', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('warning')
        batch_op.drop_column('quantity')
        batch_op.drop_column('zone')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
