"""Add z_coord to Item model

Revision ID: 9878b4a1387a
Revises: 045e30d4a92f
Create Date: 2024-10-22 15:35:28.677845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9878b4a1387a'
down_revision = '045e30d4a92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('z_coord', sa.Float(), nullable=True))
    
    # Set default value for existing rows
    op.execute('UPDATE item SET z_coord = 0.0 WHERE z_coord IS NULL')
    
    # Make the column non-nullable
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('z_coord', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('z_coord')
    # ### end Alembic commands ###
